name: MacOS ARM64

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:
  macos-arm64:
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Install dependencies
        run: brew install fftw --formula

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_SUFFIX=macos-arm64

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config Release

      - name: Check build results
        run: |
          file build/cli/vibra*
          file build/lib/libvibra*

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vibra-macos-arm64
          path: |
            build/cli/vibra*
            build/lib/libvibra*
