name: Linux AMD64

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:
  linux-amd64:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libfftw3-dev libcurl4-openssl-dev

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_SUFFIX=linux-amd64

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config Release

      - name: Check build results
        run: |
          file build/cli/vibra*
          file build/lib/libvibra*

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vibra-linux-amd64
          path: |
            build/cli/vibra*
            build/lib/libvibra*
