name: Release

on:
  workflow_dispatch:

jobs:
  native-build:
    strategy:
      fail-fast: false
      matrix:
        # https://github.com/actions/runner-images#available-images
        include:
          - id: linux-amd64
            os: ubuntu-22.04
          - id: linux-arm64
            os: ubuntu-22.04-arm
          - id: macos-amd64
            os: macos-13 # macos-14-large is non-free
          - id: macos-arm64
            os: macos-14
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies on Linux
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libfftw3-dev libcurl4-openssl-dev

      - name: Install dependencies on macOS
        if: startsWith(matrix.os, 'macos')
        run: brew install fftw --formula

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_SUFFIX=${{ matrix.id }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config Release

      - name: Check build results
        run: |
          file build/cli/vibra*
          file build/lib/libvibra*

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vibra-${{ matrix.id }}
          path: |
            build/cli/vibra*
            build/lib/libvibra*
